### ISSUE TITLE
start project

### ISSUE THREAD

**Issue by quocson1** [20chix/Expo_tutorial#2]
how to start project ???

**Comment by 20chix** [comment]
download Expo XDE, then start from template

**Comment by quocson1** [comment]
npm start ???

**Comment by 20chix** [comment]
https://www.youtube.com/watch?v=yuaE8_nXmeY

**Comment by quocson1** [comment]
https://github.com/mcnamee/react-native-starter-kit  Can you help me add Push Notifications expo to my project ? ??
